# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20b422a757cb1f2f2c02d4e2746b35a8b0821558903fd3f8dbf50088f046da44b5a19ab0ef682b505f234bbb5184e0a4223a0f76abbe7114e1200f889113d3d7

test:
  secret_key_base: 0f4942ef585fa0afa0b1c06e22659a37608e52e93a111cd8a9a36042b9452cd6e7ea9b5a18ed78cf8d264479f904e7308aaaa6b80c8db4d47fe578ca659b665c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
